"""Utilities for constructing multi-bunch filling patterns."""

from collections.abc import Mapping

import numpy as np


def _integer_parameter(
    config: Mapping[str, object],
    name: str,
    *,
    minimum: int = 1,
) -> int:
    if name not in config:
        raise ValueError(f"Missing required fill-pattern parameter '{name}'.")

    value = config[name]
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"Fill-pattern parameter '{name}' must be an integer.")
    if value < minimum:
        raise ValueError(
            f"Fill-pattern parameter '{name}' must be at least {minimum}."
        )
    return value


def _validate_n_bunches(
    config: Mapping[str, object],
    expected_n_bunches: int,
) -> None:
    if "n_bunches" not in config:
        return

    configured_n_bunches = _integer_parameter(config, "n_bunches")
    if configured_n_bunches != expected_n_bunches:
        raise ValueError(
            f"n_bunches={configured_n_bunches} does not match the "
            f"{expected_n_bunches} bunches generated by the fill pattern."
        )


def _uniform_buckets(
    harmonic_number: int,
    config: Mapping[str, object],
) -> np.ndarray:
    n_bunches = _integer_parameter(config, "n_bunches")
    if harmonic_number % n_bunches != 0:
        raise ValueError(
            f"Cannot distribute {n_bunches} bunches equidistantly over "
            f"{harmonic_number} RF buckets."
        )

    bucket_spacing = harmonic_number // n_bunches
    return np.arange(0, harmonic_number, bucket_spacing, dtype=int)


def _train_buckets(
    harmonic_number: int,
    config: Mapping[str, object],
) -> np.ndarray:
    n_trains = _integer_parameter(config, "n_trains")
    bunches_per_train = _integer_parameter(config, "bunches_per_train")
    gap_buckets = _integer_parameter(config, "gap_buckets", minimum=0)
    train_period = bunches_per_train + gap_buckets

    if n_trains * train_period != harmonic_number:
        raise ValueError(
            "Train fill must occupy exactly one ring circumference: "
            "n_trains * (bunches_per_train + gap_buckets) must equal "
            f"{harmonic_number}."
        )

    buckets = np.concatenate(
        [
            np.arange(
                train_number * train_period,
                train_number * train_period + bunches_per_train,
                dtype=int,
            )
            for train_number in range(n_trains)
        ]
    )
    _validate_n_bunches(config, len(buckets))
    return buckets


def _explicit_buckets(
    harmonic_number: int,
    config: Mapping[str, object],
) -> np.ndarray:
    if "filled_buckets" not in config:
        raise ValueError(
            "Missing required fill-pattern parameter 'filled_buckets'."
        )

    values = config["filled_buckets"]
    if not isinstance(values, list) or not values:
        raise ValueError("'filled_buckets' must be a non-empty list of integers.")
    if any(isinstance(value, bool) or not isinstance(value, int) for value in values):
        raise ValueError("'filled_buckets' must contain only integers.")

    buckets = np.asarray(values, dtype=int)
    if np.any((buckets < 0) | (buckets >= harmonic_number)):
        raise ValueError(
            f"'filled_buckets' values must be between 0 and "
            f"{harmonic_number - 1}."
        )
    if len(np.unique(buckets)) != len(buckets):
        raise ValueError("'filled_buckets' must not contain duplicates.")

    _validate_n_bunches(config, len(buckets))
    return np.sort(buckets)


def build_filling_pattern(
    harmonic_number: int,
    bunch_current: float,
    config: Mapping[str, object],
) -> np.ndarray:
    """Build the per-bucket current array used by ``Beam.init_beam``.

    If ``fill_pattern`` is omitted, every RF bucket is filled to preserve the
    legacy behavior. Supported explicit modes are ``uniform``, ``trains``, and
    ``explicit``.
    """
    if isinstance(harmonic_number, bool) or not isinstance(harmonic_number, int):
        raise ValueError("harmonic_number must be an integer.")
    if harmonic_number <= 0:
        raise ValueError("harmonic_number must be positive.")
    if (
        isinstance(bunch_current, bool)
        or not isinstance(bunch_current, (int, float))
        or not np.isfinite(bunch_current)
        or bunch_current <= 0
    ):
        raise ValueError("bunch_current must be a positive finite number.")

    fill_pattern = config.get("fill_pattern")
    if fill_pattern is None:
        buckets = np.arange(harmonic_number, dtype=int)
        _validate_n_bunches(config, harmonic_number)
    elif not isinstance(fill_pattern, str):
        raise ValueError("fill_pattern must be a string.")
    elif fill_pattern == "uniform":
        buckets = _uniform_buckets(harmonic_number, config)
    elif fill_pattern == "trains":
        buckets = _train_buckets(harmonic_number, config)
    elif fill_pattern == "explicit":
        buckets = _explicit_buckets(harmonic_number, config)
    else:
        raise ValueError(
            "Unsupported fill_pattern. Use 'uniform', 'trains', or 'explicit'."
        )

    filling_pattern = np.zeros(harmonic_number, dtype=float)
    filling_pattern[buckets] = bunch_current
    return filling_pattern
