# 32 equidistant bunches, one bunch every 13 RF buckets.

title = "vertical coupled-bunch instability 32-bunch chromaticity scan"

[environment]
container = "mbtrack2"
mount_source = ["/ccc/work/cont003/soleil/gubaiduv/transverse_instabilities/", "/ccc/work/cont003/soleil/gubaiduv/facilities_mbtrack2/"]
mount_destination = ["/home/dockeruser/transverse_instabilities/", "/home/dockeruser/facilities_mbtrack2/"]
server = "ccrt"

[job]
name = "tcbi_ver_32b"
time = 86000
n_cpu = 1
n_tasks = 32
partition = "milan"
err_folder = "/ccc/work/cont003/soleil/gubaiduv/err/"
out_folder = "/ccc/work/cont003/soleil/gubaiduv/out/"
is_gpu = false

[script]
name = "/home/dockeruser/transverse_instabilities/src/simulation/track_mb.py"
folder = "/home/dockeruser/transverse_instabilities/data/raw/tcbi_ver_32b/"
n_turns = 30000
n_macroparticles = 50_000
n_bin = 100
include_Zlong = true
id_state = "open"
ibs = true
bunch_current = 0.00625
wake_types = ["Wydip", "Wyquad"]
fill_pattern = "uniform"
n_bunches = 32

[scan]
sc = [false]
harmonic_cavity = [false]
feedback_tau = [0, 100]
feedback_phase = [-90]
Qp_x = 1.8
Qp_y = [-1.0, -0.5, -0.1, 0.1, 0.5, 1.0, 1.4, 1.6, 1.8, 2.0, 2.5]
# Qp_y = [-1.0]
